# Question

Will the code work? Why or why not?

```js
const getUsers = async () => {
  const url = 'https://jsonplaceholder.typicode.com/users';
  const users = await fetch(url).then(r => r.json()).catch((err) => []);
  console.log(users)
  return users;
}
getUsers()
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer
This code would work because all it's doing is calling a `.then` and `,catch` on an already resolved promise. First it would wait for the promise to be resolved due to the `await` keyword and then the rest of the code wouild run after.


# Teacher Feedback
Score: 3/3
Nice!